/*
window.alert("alert for no Indian scammers who don't wear deoderant");
window.alert("Damn i cant use my own website");
 */

/* window.alert("alert for no Indian scammers who don't wear deoderant");
window.alert("Damn i cant use my own website");


document.getElementById("hi").textContent = "dO Not rEeDeEM iT";

document.getElementById("hi").style.color = "red";
document.getElementById("hi").style.display = "none";
document.getElementById("hi").style.display = "";
document.getElementById("hi").style.display = "src";


let Price;
Price = 200;
console.log(Price);

let Email;

Email = "vNara2@ocdsb.ca";

console.log(Email);
console.log(typeof Email);
console.log(typeof Price);
 */


let Score;
Score = 99.9;
console.log(Score);

let isHi = true;
console.log(typeof isHi);
console.log(isHi);

let iscarforsale = true;
console.log(typeof iscarforsale);
console.log(iscarforsale);

let Name = "Vishnu narayanayanayanayanan";
let age = 27;
let student = true;

document.getElementById("wing").textContent = `Your name is ${Name}`;

document.getElementById("wing2").textContent = `You are ${age}yrs old `;

document.getElementById("arrow").textContent = `Your a ${student} at Maplewood secondary School`;